### PR TITLE
Add snow cover quality based on Landsat8 QA band

### PR DESCRIPTION
**Pull request by joferkington**
For Landsat mosaics, it would be useful to be able to use the snow/ice cover stored in the QA band.  The QA band is already used for cloud cover, so it shouldn't add a significant overhead to have an option for snow cover as well.

This PR currently doesn't have any tests for snow cover... I need to add some, but wanted to discuss whether or not adding snow cover was worthwhile first.

### CODE REVIEW

**Comment by joferkington** [comment]
Closing this PR until I get some further issues sorted out...

**Comment by pl-nfwarmerdam** [comment]
LGTM

I'd like you to add a test, though I imagine adding this in saojose_tests.py would be hard since I assume there is no snow there.

**Comment by joferkington** [comment]
@pl-nfwarmerdam - My apologies for the delay on adding the tests -- Got caught up in other things.  I've added a basic test with a landsat quality band with snow, clouds, and cirrus.

**Comment by pl-nfwarmerdam** [comment]
LGTM

**Pull request merged**
